name: build

on:
    push:
        branches: [master]
        tags: ["v*"]
    pull_request:
        branches: [master]

permissions:
    contents: write

jobs:
    build-go:
        strategy:
            fail-fast: false
            matrix:
                platform: [ubuntu-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  submodules: recursive

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version: "1.25.1"
                  cache: true

            - name: Download dependencies
              run: go mod download

            - name: Lint
              uses: golangci/golangci-lint-action@v8
              with:
                  version: latest
                  args: --timeout=5m

            - name: Build
              run: go build -v ./...

            - name: Test & Coverage
              run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

            - name: Upload coverage
              uses: codecov/codecov-action@v5
              if: matrix.platform == 'ubuntu-latest'
              with:
                  files: ./coverage.out
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Generate changelog
              if: startsWith(github.ref, 'refs/tags/')
              uses: orhun/git-cliff-action@v4
              id: git-cliff
              with:
                  config: cliff.toml
                  args: -vv --latest --strip header
              env:
                  OUTPUT: CHANGELOG.md

            - name: Release
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v2
              with:
                  body: ${{ steps.git-cliff.outputs.content }}
                  files: |
                      coverage.out
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    changelog:
        needs: build-go
        if: github.event_name == 'push' && github.ref_name == 'master'
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0
                  ref: ${{ github.head_ref || github.ref_name }}

            - name: Generate CHANGELOG
              uses: orhun/git-cliff-action@v4
              with:
                  args: --output CHANGELOG.md

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "chore: update CHANGELOG.md"
                  file_pattern: CHANGELOG.md
